name: Docker

on:
    push:
        branches:
            - master
        tags:
            - "*"
    workflow_dispatch:

env:
    MAIN_DISTRO: debian
    GHCR_IMAGE: ghcr.io/${{ github.repository_owner }}/epgstation
    DH_IMAGE: ${{ secrets.DOCKERHUB_IMAGE }}

jobs:
    build:
        strategy:
            matrix:
                distro:
                    - alpine
                    - debian
                include:
                    - distro: alpine
                      platforms: >-
                          linux/amd64,
                          linux/arm/v6,
                          linux/arm/v7,
                          linux/arm64/v8,
                    - distro: debian
                      # docker/setup-*-action has not supported linux/arm/v5.
                      platforms: >-
                          linux/amd64,
                          linux/arm/v7,
                          linux/arm64/v8,
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - name: Docker tags
              id: docker-tags
              run: |
                  GHCR="${{ env.GHCR_IMAGE }}"
                  DH="${{ env.DH_IMAGE }}"
                  if echo "$GITHUB_REF" | grep -e '^refs/heads/' >/dev/null 2>&1; then
                    GIT_BRANCH=$(echo "$GITHUB_REF" | sed -e 's|^refs/heads/||')
                    TAGS="$GHCR:$GIT_BRANCH-${{ matrix.distro }},$DH:$GIT_BRANCH-${{ matrix.distro }}"
                    if [ "$MAIN_DISTRO" = "${{ matrix.distro }}" ]; then
                      TAGS="$TAGS,$GHCR:$GIT_BRANCH,$DH:$GIT_BRANCH"
                    fi
                  else
                    GIT_TAG=$(echo "$GITHUB_REF" | sed -e 's|^refs/tags/||')
                    TAGS="$GHCR:$GIT_TAG-${{ matrix.distro }},$DH:$GIT_TAG-${{ matrix.distro }}"
                    if [ "$MAIN_DISTRO" = "${{ matrix.distro }}" ]; then
                      TAGS="$TAGS,$GHCR:$GIT_TAG,$DH:$GIT_TAG"
                    fi
                    # Always update latest image tags when a new git tag is created.
                    TAGS="$TAGS,$GHCR:${{ matrix.distro }},$DH:${{ matrix.distro }}"
                    if [ "$MAIN_DISTRO" = "${{ matrix.distro }}" ]; then
                      TAGS="$TAGS,$GHCR:latest,$DH:latest"
                    fi
                  fi
                  echo "Tags: $TAGS"
                  echo "tags=$TAGS" >> "$GITHUB_OUTPUT"
            - name: Setup QEMU user-mode emulation
              uses: docker/setup-qemu-action@v3
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Cache Docker layers
              uses: actions/cache@v4
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ matrix.distro }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-${{ matrix.distro }}-
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USER }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: Dockerfile.${{ matrix.distro }}
                  platforms: ${{ matrix.platforms }}
                  tags: ${{ steps.docker-tags.outputs.tags }}
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache
                  push: true
